kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-toyou-driver
spec:
  selector:
    matchLabels:
      app: csi-toyou-driver
  template:
    metadata:
      labels:
        app: csi-toyou-driver
    spec:
      serviceAccountName: block-csi-nodeplugin
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: csi-toyou-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: hero74/toyou-csi:v1.0.1
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--maxvolume=255"
            - "--config=/etc/config/config.yaml"
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: /tcsi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /tcsi
              name: tcsi-socket
        - name: driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          args:
            - "--v=5"
            - "--csi-address=/tcsi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.toyou.com/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /tcsi
              name: tcsi-socket
      volumes:
        - name: tcsi-socket
          hostPath:
            path: /tcsi
            type: DirectoryOrCreate
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.toyou.com
            type: DirectoryOrCreate
          name: socket-dir