# This YAML file demonstrates how to deploy the external
# resizer for use with the mock CSI driver. It
# depends on the RBAC definitions from rbac.yaml.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-sidecar-iscsi-resizer
spec:
  replicas: 2
  selector:
    matchLabels:
      external-resizer: csi-sidecar-iscsi-resizer
  template:
    metadata:
      labels:
        external-resizer: csi-sidecar-iscsi-resizer
    spec:
      serviceAccountName: block-csi-resizer
      containers:
        - name: block-csi-resizer
          image: quay.io/k8scsi/csi-resizer:v1.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /tcsi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /tcsi
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.toyou.com
            type: DirectoryOrCreate
        - name: timezone
          hostPath:
            path: /etc/localtime
