kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-toyou-driver
spec:
  selector:
    matchLabels:
      app: csi-toyou-driver
  template:
    metadata:
      labels:
        app: csi-toyou-driver
    spec:
      initContainers:
        - name: create-socket-dir
          image: busybox
          command: [ "mkdir", "-p", "/var/lib/kubelet/plugins/csi.toyou.com" ]
          volumeMounts:
            - mountPath: /var/lib/kubelet/plugins/csi.toyou.com
              name: socket-dir
      serviceAccountName: block-csi-nodeplugin
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: csi-toyou-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: hero74/toyou-csi:v1.0.1
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--maxvolume=255"
            - "--config=/etc/config/config.yaml"
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///tcsi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /tcsi
              name: socket-dir
            - mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
              name: plugins-dir
            - name: credentials
              mountPath: /etc/config/config.yaml
              subPath: config.yaml
        - name: driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v2.1.0
          args:
            - "--v=5"
            - "--csi-address=/tcsi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.toyou.com/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /tcsi
            - name: registration-dir
              mountPath: /registration
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.toyou.com
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: plugins-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
        - name: credentials
          secret:
            secretName: tyds-credential
