apiVersion: v1
kind: Pod
metadata:
  name: csi-toyou-demo-pod
spec:
  containers:
   - name: web-server
     image: nginx 
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: iscsi-pvc
       readOnly: false

