apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toyou-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-toyou-storageclass
