apiVersion: v1
kind: Pod
metadata:
  name: csiiscsi-demo-pod
spec:
  containers:
    - name: web-server
      image: nginx
      volumeDevices:
        - devicePath: /dev/block
          name: mypvc
      imagePullPolicy: IfNotPresent
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: iscsi-pvc
        readOnly: false

