apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-demo
spec:
  volumeSnapshotClassName: test-snapshotclass
  source:
    persistentVolumeClaimName: toyou-test-pvc