apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-toyou-storageclass
provisioner: csi.toyou.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  iqn: iqn.2024-01.example.server:storage.target00
reclaimPolicy: Delete
