# Deprecated in v1.16 in favor of apiextensions.k8s.io/v1
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: accesspaths.tyds.toyou.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: tyds.toyou.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: accesspaths
    # singular name to be used as an alias on the CLI and for display
    singular: accesspath
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AccessPath
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ap
  # preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
              pattern: "^[0-9a-zA-Z_-]{1,128}$"
            type:
              type: string
            gateway:
              type: string
            cluster_info:
              description: "cluster info include configuration of storage cluster"
              type: object
              properties:
                xmsServers:
                  type: string
                  description: "separated by comma. sds admin IP, used as XMS API endpoint. Both 10.252.90.101 and 10.252.90.101:8051 and 10.252.90.101,10.252.90.102 is legal value"
                secret_namespace:
                  type: string
                  description: "namespace of the secret"
                secret_name:
                  type: string
                  description: "secret include credentials for tyds cluster. secret should contains keys:token,username,password)"
                username:
                  type: string
                  description: "SDS user name. should use this field for debug only"
                password:
                  type: string
                  description: "SDS password. should use this field for debug only"
            vip_group:
              type: object
              description: "Vip group applied to the accessPath"
              properties:
                name:
                  type: string
                preempt:
                  type: boolean
                vips:
                  type: array
                  description: "Define vip under the vip group. However, only one vip is supported currently"
                  items:
                    type: object
                    properties:
                      vip:
                        description: "Virtual IP"
                        type: string
                        pattern: "(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
                      mask:
                        description: "Mask code should be in numeric format e.g.32/24/26/8"
                        type: integer
                      default_gateway:
                        description: "Preferred gateway. Controller will assign gateway randomly if this property is unset"
                        type: string
        status:
          description: "AccessPath status, This field is readonly"
          type: object
          properties:
            phase:
              type: string
            reason:
              type: string
            access_path_status:
              type: object
              properties:
                status:
                  type: string
                action_status:
                  type: string
                reason:
                  type: string
            gateway_status:
              type: object
              properties:
                desired_count:
                  type: integer
                actual_count:
                  type: integer
                reason:
                  type: string
            vip_group_status:
              type: object
              properties:
                status:
                  type: string
                action_status:
                  type: string
                reason:
                  type: string